version: '3'
networks:
  dnp:
    name: dnp
    driver: bridge
services:
  nginx:
    image: nginx
    container_name: dnp-n
    restart: always
    ports:
      - "${NG_PORT}:80"
      - "${NG_PORTS}:443"
    volumes:
      - $PWD/env/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/env/nginx/conf.d:/etc/nginx/conf.d
      - ${APPDIR}:/home/www
    networks:
      dnp:
        aliases:
          - nginx
  mysql:
    networks:
      dnp:
        aliases:
          - mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    image: mysql/mysql-server:latest
    container_name: dnp-m
    restart: always
    volumes:
        - ${DBDIR}:/var/lib/mysql
  php:
    networks:
      dnp:
        aliases:
          - dnp-p
    build: 
      context: $PWD/env/php
      dockerfile: Dockerfile
    image: php
    container_name: dnp-app
    restart: always
    privileged: true
    volumes:
      - ${APPDIR}:/home/www:rw
      - $PWD/env/php/conf:/usr/local/etc/php
    