version: '3'
networks:
  dnp:
    name: dnp
    driver: bridge
services:
  nginx:
    image: nginx
    container_name: dnp-n
    restart: always
    ports:
      - "1880:80"
      - "443:443"
    volumes:
      - $PWD/env/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/env/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/code/server:/home/www/server
    networks:
      dnp:
        aliases:
          - nginx
  mysql:
    networks:
      dnp:
        aliases:
          - mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    image: mysql/mysql-server:latest
    container_name: dnp-m
  #  restart: always
    volumes:
        - $PWD/db:/var/lib/mysql
    ports:
        - 33063:3306
  php:
    networks:
      dnp:
        aliases:
          - dnp-p
    # image: php:5.6-fpm
    # image: php:7.4.28-fpm
    build: 
      context: $PWD/env/php
      dockerfile: Dockerfile
    container_name: dnp-app
    restart: always
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - $PWD/code/server:/home/www/server:rw
      - $PWD/env/php/conf:/usr/local/etc/php
    